-- require("TheAltF4Stream.vim")
-- require("TheAltF4Stream.theme")
-- require("TheAltF4Stream.languages")
-- require("TheAltF4Stream.telescope")
-- require("TheAltF4Stream.floaterm")
-- require("TheAltF4Stream.chatgpt")
-- require("TheAltF4Stream.copilot")
-- require("TheAltF4Stream.print")
require("TheAltF4Stream.kickstart")
