print("lua")
	require("user-nvim.options")
	-- require("user.autocmds").init()
	-- require("user.cmp").init()
	-- require("user.format").init()
	-- require("user.lsp").init()
	-- -- require("user.lualine").init()
	-- require("user.others").init()
	require("user-nvim.telescope").init()
	require("user-nvim.themes")
	-- require("user.treesitter").init()

